name: "Release Build"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Add version to file
        run: mv auto-cli.bat auto-cli-${{ env.RELEASE_VERSION }}.bat
      - name: Publish the release
        run: |
            gh release create "${{ env.RELEASE_VERSION }}" \
            --title "${{ env.RELEASE_VERSION }}" \
            --generate-notes \
            auto-cli-${{ env.RELEASE_VERSION }}.bat
      - name: Update the README link
        run: |
            sed -i -E 's/v[0-9]+\.[0-9]+/${{ env.RELEASE_VERSION }}/g' README.md
        env:
            GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'